[project]
name = "c2rust-experiments"
version = "0.1.0"
description = "Infrastructure to support C-to-Rust translation with verification experiments"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.18.2",
    "openai>=2.1.0",
    "ruff>=0.13.3",
    "semver>=3.0.4",
]
